# Generated by Django 2.2.2 on 2020-05-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Attachment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
