# Generated by Django 2.2.2 on 2020-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20200517_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='screen_mode',
            field=models.IntegerField(choices=[(0, 'light-mode'), (1, 'dark-mode')], default=0),
        ),
    ]
