# Generated by Django 2.2.2 on 2020-05-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created',)},
        ),
    ]
