# Generated by Django 2.2.2 on 2020-05-23 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20200517_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='language',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.TextField(default='Mumbai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='cost_per_person',
            field=models.BigIntegerField(default=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='languages',
            field=models.ManyToManyField(related_name='events', to='session.Language'),
        ),
        migrations.AddField(
            model_name='event',
            name='terms_and_conditions',
            field=models.TextField(default='Important!'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='session.Tags'),
        ),
    ]
