# Generated by Django 2.2.2 on 2020-05-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20200523_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
