# Generated by Django 2.2.2 on 2020-05-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_event_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.TextField(default='2 hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.TextField(default='San Pada'),
            preserve_default=False,
        ),
    ]
