# Generated by Django 2.2.2 on 2020-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20200524_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='registration_type',
            field=models.CharField(choices=[('Self', 'Self'), ('Group', 'Group'), ('Corporate', 'Corporate'), ('Others', 'Others')], default='self', max_length=20),
        ),
    ]
