# Generated by Django 2.2.2 on 2020-05-13 19:39

import bookit.common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('global', 'global'), ('avatars', 'avatars'), ('id_cards', 'id_cards')], default='global', max_length=20)),
                ('path', models.FileField(upload_to=bookit.common.models.content_file_name)),
                ('file_type', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('hash_value', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
